### ISSUE TITLE
Error throws when output is not defined.

### ISSUE THREAD

**Issue by aha-oretama** [presidenten/wdio-video-reporter#6]
**Describe the bug**
If `config.output` and `options.logFile` are not defined, throw an error.
https://github.com/presidenten/wdio-video-reporter/blob/master/src/index.js#L21

**Log**
```
[0-0] 2019-05-09T06:13:52.843Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'replace' of undefined
     at new Video (/Users/aha-oretama/IdeaProjects/mercari-web-jp-e2e-test/node_modules/wdio-video-reporter/dist/wdio-video-reporter.js:183:61)
     at BaseReporter.initReporter (/Users/aha-oretama/IdeaProjects/mercari-web-jp-e2e-test/node_modules/@wdio/runner/build/reporter.js:172:14)
     at Array.map (<anonymous>)
     at new BaseReporter (/Users/aha-oretama/IdeaProjects/mercari-web-jp-e2e-test/node_modules/@wdio/runner/build/reporter.js:42:39)
     at Runner.run (/Users/aha-oretama/IdeaProjects/mercari-web-jp-e2e-test/node_modules/@wdio/runner/build/index.js:91:21)
     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**To Reproduce**
config -> output is not defined in wdio.conf.js.

**Expected behavior**
I think you should define default output directory.
Other report(such as Allure report) defines default directory as follows.
https://webdriver.io/docs/allure-reporter.html

**Environment (please complete the following information):**
 - **wdio-video-reporter version:1.3.1
 - **WebdriverIO version:5.8.3

**Comment by presidenten** [comment]
Thats a good idea. Ill have a look at it in a day or so.

**Comment by presidenten** [comment]
Fixed in patch release 1.3.2

**Comment by aha-oretama** [comment]
Thanks!

**Comment by presidenten** [comment]
Please update to ^1.3.4 for better allure custom outputDir handling
